#' Label formula
#' @description \code{label_formula()} can be used to parse text label to expression
#' or richtext, and displays labels as math formula.
#' @param parse logical or function generated by \code{parse_func()}.
#' @return a label function.
#' @rdname label_formula
#' @author Hou Yun
#' @export
label_formula <- function (parse = TRUE) {
  force(parse)
  function(x) {
    if (length(x) < 1) {
      return(character(0))
    }
    if (!is.function(parse) && !isTRUE(parse)) {
      return(x)
    }

    n <- length(x)
    nm <- names(x)
    .FUN <- parse
    print(parse)
    if (!is.function(.FUN)) {
      if (any(grepl("\n", x, fixed = TRUE))) {
        .FUN <- parse_func(output = "richtext")
      } else {
        .FUN <- parse_func(output = "character")
      }
    }
    x <- .FUN(x)

    if (!is_richtext(x)) {
      x <- parse_safe(x)
    }
    if (is_richtext(x)) {
      message("It should be used in conjunction with 'ggtext::element_markdown()'.")
    }
    names(x) <- nm
    x
  }
}
